# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'pyqt4_viewer.ui'
#
# Created: Tue Feb 16 10:15:27 2010
#      by: PyQt4 UI code generator 4.7
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1076, 574)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(380, 350, 311, 121))
        self.tabWidget.setAutoFillBackground(False)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.img_tab = QtGui.QWidget()
        self.img_tab.setObjectName("img_tab")
        self.groupBox = QtGui.QGroupBox(self.img_tab)
        self.groupBox.setEnabled(True)
        self.groupBox.setGeometry(QtCore.QRect(139, 0, 151, 81))
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtGui.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 121, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_6 = QtGui.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.worldspace_button = QtGui.QRadioButton(self.layoutWidget)
        self.worldspace_button.setChecked(True)
        self.worldspace_button.setObjectName("worldspace_button")
        self.verticalLayout_6.addWidget(self.worldspace_button)
        self.voxspace_button = QtGui.QRadioButton(self.layoutWidget)
        self.voxspace_button.setChecked(False)
        self.voxspace_button.setObjectName("voxspace_button")
        self.verticalLayout_6.addWidget(self.voxspace_button)
        self.layoutWidget1 = QtGui.QWidget(self.img_tab)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 10, 111, 56))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.cmap_box = QtGui.QComboBox(self.layoutWidget1)
        self.cmap_box.setObjectName("cmap_box")
        self.verticalLayout_4.addWidget(self.cmap_box)
        self.interp_box = QtGui.QComboBox(self.layoutWidget1)
        self.interp_box.setObjectName("interp_box")
        self.verticalLayout_4.addWidget(self.interp_box)
        self.tabWidget.addTab(self.img_tab, "")
        self.over_tab = QtGui.QWidget()
        self.over_tab.setObjectName("over_tab")
        self.label = QtGui.QLabel(self.over_tab)
        self.label.setGeometry(QtCore.QRect(150, 10, 99, 17))
        self.label.setObjectName("label")
        self.o_alpha_slider = QtGui.QSlider(self.over_tab)
        self.o_alpha_slider.setGeometry(QtCore.QRect(150, 30, 101, 22))
        self.o_alpha_slider.setMaximum(100)
        self.o_alpha_slider.setSingleStep(1)
        self.o_alpha_slider.setProperty("value", 99)
        self.o_alpha_slider.setOrientation(QtCore.Qt.Horizontal)
        self.o_alpha_slider.setObjectName("o_alpha_slider")
        self.layoutWidget2 = QtGui.QWidget(self.over_tab)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 10, 111, 56))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.o_cmap_box = QtGui.QComboBox(self.layoutWidget2)
        self.o_cmap_box.setObjectName("o_cmap_box")
        self.verticalLayout_2.addWidget(self.o_cmap_box)
        self.o_interp_box = QtGui.QComboBox(self.layoutWidget2)
        self.o_interp_box.setObjectName("o_interp_box")
        self.verticalLayout_2.addWidget(self.o_interp_box)
        self.tabWidget.addTab(self.over_tab, "")
        self.layoutWidget3 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(80, 340, 226, 172))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_7 = QtGui.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtGui.QLabel(self.layoutWidget3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.label_4 = QtGui.QLabel(self.layoutWidget3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_3.addWidget(self.label_4)
        self.label_5 = QtGui.QLabel(self.layoutWidget3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_3.addWidget(self.label_5)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.sag_slider = QtGui.QSlider(self.layoutWidget3)
        self.sag_slider.setMinimumSize(QtCore.QSize(157, 0))
        self.sag_slider.setOrientation(QtCore.Qt.Horizontal)
        self.sag_slider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.sag_slider.setObjectName("sag_slider")
        self.verticalLayout.addWidget(self.sag_slider)
        self.cor_slider = QtGui.QSlider(self.layoutWidget3)
        self.cor_slider.setOrientation(QtCore.Qt.Horizontal)
        self.cor_slider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.cor_slider.setObjectName("cor_slider")
        self.verticalLayout.addWidget(self.cor_slider)
        self.axi_slider = QtGui.QSlider(self.layoutWidget3)
        self.axi_slider.setMinimumSize(QtCore.QSize(157, 0))
        self.axi_slider.setOrientation(QtCore.Qt.Horizontal)
        self.axi_slider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.axi_slider.setObjectName("axi_slider")
        self.verticalLayout.addWidget(self.axi_slider)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_2)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.sag_spinner = QtGui.QDoubleSpinBox(self.layoutWidget3)
        self.sag_spinner.setAlignment(QtCore.Qt.AlignCenter)
        self.sag_spinner.setButtonSymbols(QtGui.QAbstractSpinBox.UpDownArrows)
        self.sag_spinner.setObjectName("sag_spinner")
        self.horizontalLayout_6.addWidget(self.sag_spinner)
        self.cor_spinner = QtGui.QDoubleSpinBox(self.layoutWidget3)
        self.cor_spinner.setAlignment(QtCore.Qt.AlignCenter)
        self.cor_spinner.setObjectName("cor_spinner")
        self.horizontalLayout_6.addWidget(self.cor_spinner)
        self.axi_spinner = QtGui.QDoubleSpinBox(self.layoutWidget3)
        self.axi_spinner.setAlignment(QtCore.Qt.AlignCenter)
        self.axi_spinner.setObjectName("axi_spinner")
        self.horizontalLayout_6.addWidget(self.axi_spinner)
        self.gridLayout.addLayout(self.horizontalLayout_6, 0, 0, 1, 3)
        self.label_6 = QtGui.QLabel(self.layoutWidget3)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.layoutWidget3)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.layoutWidget3)
        self.label_8.setAutoFillBackground(False)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout)
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(730, 400, 251, 131))
        self.groupBox_2.setObjectName("groupBox_2")
        self.xyz_label = QtGui.QLabel(self.groupBox_2)
        self.xyz_label.setGeometry(QtCore.QRect(10, 30, 61, 17))
        self.xyz_label.setObjectName("xyz_label")
        self.vox_label = QtGui.QLabel(self.groupBox_2)
        self.vox_label.setGeometry(QtCore.QRect(10, 60, 61, 17))
        self.vox_label.setObjectName("vox_label")
        self.over_vox_label = QtGui.QLabel(self.groupBox_2)
        self.over_vox_label.setGeometry(QtCore.QRect(10, 90, 61, 17))
        self.over_vox_label.setObjectName("over_vox_label")
        self.ortho_figs_widget = MplQT4OrthoSlicesWidget(self.centralwidget)
        self.ortho_figs_widget.setGeometry(QtCore.QRect(1, 1, 1071, 330))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ortho_figs_widget.sizePolicy().hasHeightForWidth())
        self.ortho_figs_widget.setSizePolicy(sizePolicy)
        self.ortho_figs_widget.setObjectName("ortho_figs_widget")
        self.layoutWidget4 = QtGui.QWidget(self.centralwidget)
        self.layoutWidget4.setGeometry(QtCore.QRect(752, 329, 161, 61))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.layoutWidget4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtGui.QLabel(self.layoutWidget4)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.zoom_box = QtGui.QComboBox(self.layoutWidget4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.zoom_box.sizePolicy().hasHeightForWidth())
        self.zoom_box.setSizePolicy(sizePolicy)
        self.zoom_box.setIconSize(QtCore.QSize(16, 16))
        self.zoom_box.setObjectName("zoom_box")
        self.zoom_box.addItem("")
        self.zoom_box.addItem("")
        self.zoom_box.addItem("")
        self.zoom_box.addItem("")
        self.zoom_box.addItem("")
        self.zoom_box.addItem("")
        self.verticalLayout_5.addWidget(self.zoom_box)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1076, 22))
        self.menubar.setObjectName("menubar")
        self.menuLoad_Image = QtGui.QMenu(self.menubar)
        self.menuLoad_Image.setObjectName("menuLoad_Image")
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        self.menuTools = QtGui.QMenu(self.menubar)
        self.menuTools.setObjectName("menuTools")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Beam_File = QtGui.QAction(MainWindow)
        self.actionLoad_Beam_File.setObjectName("actionLoad_Beam_File")
        self.actionLoad_MR_File = QtGui.QAction(MainWindow)
        self.actionLoad_MR_File.setObjectName("actionLoad_MR_File")
        self.actionLoad_Overlay_Image = QtGui.QAction(MainWindow)
        self.actionLoad_Overlay_Image.setObjectName("actionLoad_Overlay_Image")
        self.actionUnload_Overlay = QtGui.QAction(MainWindow)
        self.actionUnload_Overlay.setObjectName("actionUnload_Overlay")
        self.actionTime_Frequency_Plane = QtGui.QAction(MainWindow)
        self.actionTime_Frequency_Plane.setCheckable(True)
        self.actionTime_Frequency_Plane.setChecked(True)
        self.actionTime_Frequency_Plane.setObjectName("actionTime_Frequency_Plane")
        self.action3D_Views = QtGui.QAction(MainWindow)
        self.action3D_Views.setCheckable(True)
        self.action3D_Views.setChecked(True)
        self.action3D_Views.setObjectName("action3D_Views")
        self.actionAnimate_Freq_Band = QtGui.QAction(MainWindow)
        self.actionAnimate_Freq_Band.setObjectName("actionAnimate_Freq_Band")
        self.menuLoad_Image.addAction(self.actionLoad_MR_File)
        self.menuLoad_Image.addAction(self.actionLoad_Beam_File)
        self.menuLoad_Image.addAction(self.actionLoad_Overlay_Image)
        self.menuLoad_Image.addAction(self.actionUnload_Overlay)
        self.menubar.addAction(self.menuLoad_Image.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuTools.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.axi_slider, QtCore.SIGNAL("sliderMoved(int)"), self.ortho_figs_widget.moveAxiPosition)
        QtCore.QObject.connect(self.cor_slider, QtCore.SIGNAL("sliderMoved(int)"), self.ortho_figs_widget.moveCorPosition)
        QtCore.QObject.connect(self.sag_slider, QtCore.SIGNAL("sliderMoved(int)"), self.ortho_figs_widget.moveSagPosition)
        QtCore.QObject.connect(self.ortho_figs_widget, QtCore.SIGNAL("x_state(int)"), self.sag_slider.setValue)
        QtCore.QObject.connect(self.ortho_figs_widget, QtCore.SIGNAL("y_state(int)"), self.cor_slider.setValue)
        QtCore.QObject.connect(self.ortho_figs_widget, QtCore.SIGNAL("z_state(int)"), self.axi_slider.setValue)
        QtCore.QObject.connect(self.ortho_figs_widget, QtCore.SIGNAL("x_state(double)"), self.sag_spinner.setValue)
        QtCore.QObject.connect(self.ortho_figs_widget, QtCore.SIGNAL("y_state(double)"), self.cor_spinner.setValue)
        QtCore.QObject.connect(self.ortho_figs_widget, QtCore.SIGNAL("z_state(double)"), self.axi_spinner.setValue)
        QtCore.QObject.connect(self.cmap_box, QtCore.SIGNAL("currentIndexChanged(QString)"), self.ortho_figs_widget.setCmap)
        QtCore.QObject.connect(self.interp_box, QtCore.SIGNAL("currentIndexChanged(QString)"), self.ortho_figs_widget.setInterp)
        QtCore.QObject.connect(self.o_cmap_box, QtCore.SIGNAL("currentIndexChanged(QString)"), self.ortho_figs_widget.setCmapO)
        QtCore.QObject.connect(self.o_interp_box, QtCore.SIGNAL("currentIndexChanged(QString)"), self.ortho_figs_widget.setInterpO)
        QtCore.QObject.connect(self.o_alpha_slider, QtCore.SIGNAL("valueChanged(int)"), self.ortho_figs_widget.setAlphaO)
        QtCore.QObject.connect(self.zoom_box, QtCore.SIGNAL("activated(int)"), self.ortho_figs_widget.zoom_slices)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.tabWidget, self.sag_slider)
        MainWindow.setTabOrder(self.sag_slider, self.cor_slider)
        MainWindow.setTabOrder(self.cor_slider, self.axi_slider)
        MainWindow.setTabOrder(self.axi_slider, self.o_alpha_slider)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setToolTip(QtGui.QApplication.translate("MainWindow", "image mapping", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setWhatsThis(QtGui.QApplication.translate("MainWindow", "image mappping", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox.setTitle(QtGui.QApplication.translate("MainWindow", "Image Space", None, QtGui.QApplication.UnicodeUTF8))
        self.worldspace_button.setText(QtGui.QApplication.translate("MainWindow", "World Space", None, QtGui.QApplication.UnicodeUTF8))
        self.voxspace_button.setText(QtGui.QApplication.translate("MainWindow", "Voxel Space", None, QtGui.QApplication.UnicodeUTF8))
        self.cmap_box.setToolTip(QtGui.QApplication.translate("MainWindow", "colormap", None, QtGui.QApplication.UnicodeUTF8))
        self.cmap_box.setWhatsThis(QtGui.QApplication.translate("MainWindow", "colormap", None, QtGui.QApplication.UnicodeUTF8))
        self.interp_box.setToolTip(QtGui.QApplication.translate("MainWindow", "interpolation", None, QtGui.QApplication.UnicodeUTF8))
        self.interp_box.setWhatsThis(QtGui.QApplication.translate("MainWindow", "interpolation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.img_tab), QtGui.QApplication.translate("MainWindow", "Image Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Overlay Opacity", None, QtGui.QApplication.UnicodeUTF8))
        self.o_alpha_slider.setToolTip(QtGui.QApplication.translate("MainWindow", "alpha mixing", None, QtGui.QApplication.UnicodeUTF8))
        self.o_alpha_slider.setWhatsThis(QtGui.QApplication.translate("MainWindow", "alpha mixing", None, QtGui.QApplication.UnicodeUTF8))
        self.o_cmap_box.setToolTip(QtGui.QApplication.translate("MainWindow", "colormap", None, QtGui.QApplication.UnicodeUTF8))
        self.o_cmap_box.setWhatsThis(QtGui.QApplication.translate("MainWindow", "colormap", None, QtGui.QApplication.UnicodeUTF8))
        self.o_interp_box.setToolTip(QtGui.QApplication.translate("MainWindow", "interpolation", None, QtGui.QApplication.UnicodeUTF8))
        self.o_interp_box.setWhatsThis(QtGui.QApplication.translate("MainWindow", "interpolation", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.over_tab), QtGui.QApplication.translate("MainWindow", "Overlay Controls", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("MainWindow", "Sagittal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("MainWindow", "Coronal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("MainWindow", "Axial", None, QtGui.QApplication.UnicodeUTF8))
        self.label_6.setText(QtGui.QApplication.translate("MainWindow", "Sagittal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("MainWindow", "Coronal", None, QtGui.QApplication.UnicodeUTF8))
        self.label_8.setText(QtGui.QApplication.translate("MainWindow", "Axial", None, QtGui.QApplication.UnicodeUTF8))
        self.groupBox_2.setTitle(QtGui.QApplication.translate("MainWindow", "Position Information", None, QtGui.QApplication.UnicodeUTF8))
        self.xyz_label.setText(QtGui.QApplication.translate("MainWindow", "mm", None, QtGui.QApplication.UnicodeUTF8))
        self.vox_label.setText(QtGui.QApplication.translate("MainWindow", "vox", None, QtGui.QApplication.UnicodeUTF8))
        self.over_vox_label.setText(QtGui.QApplication.translate("MainWindow", "over vox", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Zoom FOV Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_box.setItemText(0, QtGui.QApplication.translate("MainWindow", "Full FOV", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_box.setItemText(1, QtGui.QApplication.translate("MainWindow", "160 x 160 x 160", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_box.setItemText(2, QtGui.QApplication.translate("MainWindow", "80 x 80 x 80", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_box.setItemText(3, QtGui.QApplication.translate("MainWindow", "40 x 40 x 40", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_box.setItemText(4, QtGui.QApplication.translate("MainWindow", "20 x 20 x 20", None, QtGui.QApplication.UnicodeUTF8))
        self.zoom_box.setItemText(5, QtGui.QApplication.translate("MainWindow", "10 x 10 x 10", None, QtGui.QApplication.UnicodeUTF8))
        self.menuLoad_Image.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.menuView.setTitle(QtGui.QApplication.translate("MainWindow", "View", None, QtGui.QApplication.UnicodeUTF8))
        self.menuTools.setTitle(QtGui.QApplication.translate("MainWindow", "Tools", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Beam_File.setText(QtGui.QApplication.translate("MainWindow", "Load Beam File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_MR_File.setText(QtGui.QApplication.translate("MainWindow", "Load MR File", None, QtGui.QApplication.UnicodeUTF8))
        self.actionLoad_Overlay_Image.setText(QtGui.QApplication.translate("MainWindow", "Load Overlay Image", None, QtGui.QApplication.UnicodeUTF8))
        self.actionUnload_Overlay.setText(QtGui.QApplication.translate("MainWindow", "Unload Overlay", None, QtGui.QApplication.UnicodeUTF8))
        self.actionTime_Frequency_Plane.setText(QtGui.QApplication.translate("MainWindow", "Time Frequency Plane", None, QtGui.QApplication.UnicodeUTF8))
        self.action3D_Views.setText(QtGui.QApplication.translate("MainWindow", "3D Views", None, QtGui.QApplication.UnicodeUTF8))
        self.actionAnimate_Freq_Band.setText(QtGui.QApplication.translate("MainWindow", "Animate Freq Band", None, QtGui.QApplication.UnicodeUTF8))

from nutmeg.vis.qt4_widgets import MplQT4OrthoSlicesWidget
