#!/usr/bin/env python
import os
os.environ['ETS_TOOLKIT'] = 'qt4'
from PyQt4 import QtGui
import sys
import optparse

def main():
    usage = 'usage: %prog [options]'
    
    op = optparse.OptionParser(usage=usage)
    op.add_option('-m', '--main-file', dest='image',
                  help='To be plotted as a base image', type='string',
                  default=None)
    op.add_option('-o', '--overlay-file', dest='overlay',
                  help='Nifti file to use for overlays', type='string',
                  default=None)

    
    (opts, args) = op.parse_args()

    # THIS MUST HAPPEN FIRST BEFORE IMPORTING ENTHOUGHT STUFF!!!
    app = QtGui.QApplication(sys.argv)
    
    from xipy.vis.three_dee_viewer import MayaviViewer
    import xipy.volume_utils as vu
    win = MayaviViewer(image=opts.image)

    if hasattr(win, 'image') and opts.overlay is not None:
        from xipy.overlay.image_overlay import ImageOverlayManager, \
             ImageOverlayWindow
        
        oman = ImageOverlayManager(win.viewer.blender.bbox,
                                   overlay=opts.overlay)
        win.make_tool_from_functional_manager(ImageOverlayWindow, oman)

    win.show()
    return win, app

if __name__=='__main__':
    win, app = main()
    sys.exit(app.exec_())
