#!/usr/bin/env python
import os
os.environ['ETS_TOOLKIT'] = 'qt4'
from PyQt4 import QtGui
import sys
import optparse

def main():

    usage = 'usage: %prog [options]'
    
    op = optparse.OptionParser(usage=usage)
    op.add_option('-m', '--main-file', dest='image',
                  help='To be plotted as a base image', type='string',
                  default=None)
    op.add_option('-o', '--overlay-file', dest='overlay',
                  help='Nifti file to use for overlays', type='string',
                  default=None)
    op.add_option('-2', '--2donly', dest='no_mayavi_viewer',
                  action='store_true',
                  help='Do not launch the 3D viewer',
                  default=False)

    
    (opts, args) = op.parse_args()

    # THIS MUST HAPPEN FIRST BEFORE IMPORTING ENTHOUGHT STUFF!!!
    app = QtGui.QApplication(sys.argv)

    from xipy.vis.ortho_viewer import ortho_viewer
    import xipy.volume_utils as vu
    win = ortho_viewer(image=opts.image,
                       mayavi_viewer=not opts.no_mayavi_viewer)

    if hasattr(win, 'image') and opts.overlay is not None:
        from xipy.overlay.image_overlay import ImageOverlayManager, \
             ImageOverlayWindow
        
        oman = ImageOverlayManager(vu.world_limits(win.image.raw_image),
                                   overlay=opts.overlay)
        win.make_tool_from_functional_manager(ImageOverlayWindow, oman)

    win.show()
    return win, app

if __name__=='__main__':
    win, app = main()
    sys.exit(app.exec_())
