#!/usr/bin/env python
import os
os.environ['ETS_TOOLKIT'] = 'qt4'
from PyQt4 import QtGui
import sys
import optparse

def main():

    usage = 'usage: %prog [options]'
    
    op = optparse.OptionParser(usage=usage)
##     op.add_option('-m', '--main-file', dest='image',
##                   help='To be plotted as a base image', type='string',
##                   default=None)
##     op.add_option('-o', '--overlay-file', dest='overlay',
##                   help='Nifti file to use for overlays', type='string',
##                   default=None)

    
    (opts, args) = op.parse_args()

    # THIS MUST HAPPEN FIRST BEFORE IMPORTING ENTHOUGHT STUFF!!!
    app = QtGui.QApplication(sys.argv)
    
    from xipy.vis.three_dee_viewer import MayaviViewer
##     win = ortho_viewer(image=opts.image, beam=opts.beam, fliplr=opts.fliplr,
##                        overlay=opts.overlay)
    win = MayaviViewer()

    win.show()
    sys.exit(app.exec_())

if __name__=='__main__':
    main()
